export const REQUEST_PODCAST = 'REQUEST_PODCAST';
export const RECEIVE_EPISODES = 'RECEIVE_EPISODES';
export const RECEIVE_PODCAST = 'RECEIVE_PODCAST';

export const REQUEST_TOP_PODCASTS = 'REQUEST_TOP_PODCASTS';
export const RECEIVE_TOP_PODCASTS = 'RECEIVE_TOP_PODCASTS';

export const SUBSCRIBE_PODCAST = 'SUBSCRIBE_PODCAST';
export const UNSUBSCRIBE_PODCAST = 'UNSUBSCRIBE_PODCAST';

export const PLAY = 'PLAY';
export const PAUSE = 'PAUSE';
export const ENDED = 'ENDED';
export const LISTEN_EPISODE = 'LISTEN_EPISODE';

export const RECORD_TYPE_HIGHLIGHT = 'HIGHLIGHT';
export const RECORD_TYPE_FULL = 'FULL';
