// TODO: Migrate this to an actual API call
// https://api.spreaker.com/v2/show-categories
export default [
    { category_id: 92, name: 'Arts', permalink: 'arts', level: 1 },
    { category_id: 99, name: 'Business', permalink: 'business', level: 1 },
    { category_id: 106, name: 'Comedy', permalink: 'comedy', level: 1 },
    { category_id: 110, name: 'Education', permalink: 'education', level: 1 },
    { category_id: 115, name: 'Fiction', permalink: 'fiction', level: 1 },
    { category_id: 119, name: 'Government', permalink: 'government', level: 1 },
    { category_id: 121, name: 'Health & Fitness', permalink: 'health-fitness', level: 1 },
    { category_id: 120, name: 'History', permalink: 'history', level: 1 },
    { category_id: 128, name: 'Kids & Family', permalink: 'kids-family', level: 1 },
    { category_id: 133, name: 'Leisure', permalink: 'leisure', level: 1 },
    { category_id: 142, name: 'Music', permalink: 'music', level: 1 },
    { category_id: 146, name: 'News', permalink: 'news', level: 1 },
    { category_id: 154, name: 'Religion & Spirituality', permalink: 'religion-spirituality', level: 1 },
    { category_id: 162, name: 'Science', permalink: 'science', level: 1 },
    { category_id: 172, name: 'Society & Culture', permalink: 'society-culture', level: 1 },
    { category_id: 178, name: 'Sports', permalink: 'sports', level: 1 },
    { category_id: 194, name: 'Technology', permalink: 'technology', level: 1 },
    { category_id: 195, name: 'True Crime', permalink: 'true-crime', level: 1 },
    { category_id: 196, name: 'TV & Film', permalink: 'tv-film', level: 1 },

    // { category_id: 93, name: 'Books', permalink: 'arts-books', level: 2 },
    // { category_id: 94, name: 'Design', permalink: 'arts-design', level: 2 },
    // { category_id: 95, name: 'Fashion & Beauty', permalink: 'arts-fashion-beauty', level: 2 },
    // { category_id: 96, name: 'Food', permalink: 'arts-food', level: 2 },
    // { category_id: 97, name: 'Performing Arts', permalink: 'arts-performing-arts', level: 2 },
    // { category_id: 98, name: 'Visual Arts', permalink: 'arts-visual-arts', level: 2 },
    // { category_id: 100, name: 'Careers', permalink: 'business-careers', level: 2 },
    // { category_id: 101, name: 'Entrepreneurship', permalink: 'business-entrepreneurship', level: 2 },
    // { category_id: 102, name: 'Investing', permalink: 'business-investing', level: 2 },
    // { category_id: 103, name: 'Management', permalink: 'business-management', level: 2 },
    // { category_id: 104, name: 'Marketing', permalink: 'business-marketing', level: 2 },
    // { category_id: 105, name: 'Non-Profit', permalink: 'business-non-profit', level: 2 },
    // { category_id: 107, name: 'Comedy Interviews', permalink: 'comedy-comedy-interviews', level: 2 },
    // { category_id: 108, name: 'Improv', permalink: 'comedy-improv', level: 2 },
    // { category_id: 109, name: 'Stand-Up', permalink: 'comedy-stand-up', level: 2 },
    // { category_id: 111, name: 'Courses', permalink: 'education-courses', level: 2 },
    // { category_id: 112, name: 'How To', permalink: 'education-how-to', level: 2 },
    // { category_id: 113, name: 'Language Learning', permalink: 'education-language-learning', level: 2 },
    // { category_id: 114, name: 'Self-Improvement', permalink: 'education-self-improvement', level: 2 },
    // { category_id: 116, name: 'Comedy Fiction', permalink: 'fiction-comedy-fiction', level: 2 },
    // { category_id: 117, name: 'Drama', permalink: 'fiction-drama', level: 2 },
    // { category_id: 118, name: 'Science Fiction', permalink: 'fiction-science-fiction', level: 2 },
    // { category_id: 122, name: 'Alternative Health', permalink: 'health-fitness-alternative-health', level: 2 },
    // { category_id: 123, name: 'Fitness', permalink: 'health-fitness-fitness', level: 2 },
    // { category_id: 124, name: 'Medicine', permalink: 'health-fitness-medicine', level: 2 },
    // { category_id: 125, name: 'Mental Health', permalink: 'health-fitness-mental-health', level: 2 },
    // { category_id: 126, name: 'Nutrition', permalink: 'health-fitness-nutrition', level: 2 },
    // { category_id: 127, name: 'Sexuality', permalink: 'health-fitness-sexuality', level: 2 },
    // { category_id: 129, name: 'Education for Kids', permalink: 'kids-family-education-for-kids', level: 2 },
    // { category_id: 130, name: 'Parenting', permalink: 'kids-family-parenting', level: 2 },
    // { category_id: 131, name: 'Pets & Animals', permalink: 'kids-family-pets-animals', level: 2 },
    // { category_id: 132, name: 'Stories for Kids', permalink: 'kids-family-stories-for-kids', level: 2 },
    // { category_id: 134, name: 'Animation & Manga', permalink: 'leisure-animation-manga', level: 2 },
    // { category_id: 135, name: 'Automotive', permalink: 'leisure-automotive', level: 2 },
    // { category_id: 136, name: 'Aviation', permalink: 'leisure-aviation', level: 2 },
    // { category_id: 137, name: 'Crafts', permalink: 'leisure-crafts', level: 2 },
    // { category_id: 138, name: 'Games', permalink: 'leisure-games', level: 2 },
    // { category_id: 139, name: 'Hobbies', permalink: 'leisure-hobbies', level: 2 },
    // { category_id: 140, name: 'Home & Garden', permalink: 'leisure-home-garden', level: 2 },
    // { category_id: 141, name: 'Video Games', permalink: 'leisure-video-games', level: 2 },
    // { category_id: 143, name: 'Music Commentary', permalink: 'music-music-commentary', level: 2 },
    // { category_id: 144, name: 'Music History', permalink: 'music-music-history', level: 2 },
    // { category_id: 145, name: 'Music Interviews', permalink: 'music-music-interviews', level: 2 },
    // { category_id: 147, name: 'Business News', permalink: 'news-business-news', level: 2 },
    // { category_id: 148, name: 'Daily News', permalink: 'news-daily-news', level: 2 },
    // { category_id: 149, name: 'Entertainment News', permalink: 'news-entertainment-news', level: 2 },
    // { category_id: 150, name: 'News Commentary', permalink: 'news-news-commentary', level: 2 },
    // { category_id: 151, name: 'Politics', permalink: 'news-politics', level: 2 },
    // { category_id: 152, name: 'Sports News', permalink: 'news-sports-news', level: 2 },
    // { category_id: 153, name: 'Tech News', permalink: 'news-tech-news', level: 2 },
    // { category_id: 155, name: 'Buddhism', permalink: 'religion-spirituality-buddhism', level: 2 },
    // { category_id: 156, name: 'Christianity', permalink: 'religion-spirituality-christianity', level: 2 },
    // { category_id: 157, name: 'Hinduism', permalink: 'religion-spirituality-hinduism', level: 2 },
    // { category_id: 158, name: 'Islam', permalink: 'religion-spirituality-islam', level: 2 },
    // { category_id: 159, name: 'Judaism', permalink: 'religion-spirituality-judaism', level: 2 },
    // { category_id: 160, name: 'Religion', permalink: 'religion-spirituality-religion', level: 2 },
    // { category_id: 161, name: 'Spirituality', permalink: 'religion-spirituality-spirituality', level: 2 },
    // { category_id: 163, name: 'Astronomy', permalink: 'science-astronomy', level: 2 },
    // { category_id: 164, name: 'Chemistry', permalink: 'science-chemistry', level: 2 },
    // { category_id: 165, name: 'Earth Sciences', permalink: 'science-earth-sciences', level: 2 },
    // { category_id: 166, name: 'Life Sciences', permalink: 'science-life-sciences', level: 2 },
    // { category_id: 167, name: 'Mathematics', permalink: 'science-mathematics', level: 2 },
    // { category_id: 168, name: 'Natural Sciences', permalink: 'science-natural-sciences', level: 2 },
    // { category_id: 169, name: 'Nature', permalink: 'science-nature', level: 2 },
    // { category_id: 170, name: 'Physics', permalink: 'science-physics', level: 2 },
    // { category_id: 171, name: 'Social Sciences', permalink: 'science-social-sciences', level: 2 },
    // { category_id: 173, name: 'Documentary', permalink: 'society-culture-documentary', level: 2 },
    // { category_id: 174, name: 'Personal Journals', permalink: 'society-culture-personal-journals', level: 2 },
    // { category_id: 175, name: 'Philosophy', permalink: 'society-culture-philosophy', level: 2 },
    // { category_id: 176, name: 'Places & Travel', permalink: 'society-culture-places-travel', level: 2 },
    // { category_id: 177, name: 'Relationships', permalink: 'society-culture-relationships', level: 2 },
    // { category_id: 179, name: 'Baseball', permalink: 'sports-baseball', level: 2 },
    // { category_id: 180, name: 'Basketball', permalink: 'sports-basketball', level: 2 },
    // { category_id: 181, name: 'Cricket', permalink: 'sports-cricket', level: 2 },
    // { category_id: 182, name: 'Fantasy Sports', permalink: 'sports-fantasy-sports', level: 2 },
    // { category_id: 183, name: 'Football', permalink: 'sports-football', level: 2 },
    // { category_id: 184, name: 'Golf', permalink: 'sports-golf', level: 2 },
    // { category_id: 185, name: 'Hockey', permalink: 'sports-hockey', level: 2 },
    // { category_id: 186, name: 'Rugby', permalink: 'sports-rugby', level: 2 },
    // { category_id: 187, name: 'Running', permalink: 'sports-running', level: 2 },
    // { category_id: 188, name: 'Soccer', permalink: 'sports-soccer', level: 2 },
    // { category_id: 189, name: 'Swimming', permalink: 'sports-swimming', level: 2 },
    // { category_id: 190, name: 'Tennis', permalink: 'sports-tennis', level: 2 },
    // { category_id: 191, name: 'Volleyball', permalink: 'sports-volleyball', level: 2 },
    // { category_id: 192, name: 'Wilderness', permalink: 'sports-wilderness', level: 2 },
    // { category_id: 193, name: 'Wrestling', permalink: 'sports-wrestling', level: 2 },
    // { category_id: 197, name: 'After Shows', permalink: 'tv-film-after-shows', level: 2 },
    // { category_id: 198, name: 'Film History', permalink: 'tv-film-film-history', level: 2 },
    // { category_id: 199, name: 'Film Interviews', permalink: 'tv-film-film-interviews', level: 2 },
    // { category_id: 200, name: 'Film Reviews', permalink: 'tv-film-film-reviews', level: 2 },
    // { category_id: 201, name: 'TV Reviews', permalink: 'tv-film-tv-reviews', level: 2 },
];
