export const REQUEST_EPISODE = 'REQUEST_EPISODE';
export const RECEIVE_EPISODE_SUCCESS = 'RECEIVE_EPISODE_SUCCESS';
export const RECEIVE_EPISODE_ERROR = 'RECEIVE_EPISODE_ERROR';

export const DOWNLOAD_EPISODE_PROGRESS = 'DOWNLOAD_EPISODE_PROGRESS';
export const DOWNLOAD_EPISODE_DONE = 'DOWNLOAD_EPISODE_DONE';
export const DOWNLOAD_EPISODE_ERROR = 'DOWNLOAD_EPISODE_ERROR';
export const DISCARD_DOWNLOADED_EPISODE = 'DISCARD_DOWNLOADED_EPISODE';
